### ISSUE TITLE
Magento2 Port

### ISSUE THREAD

**Issue by amenk** [LimeSoda/LimeSoda_EnvironmentConfiguration#10]
Are there any plans for a Magento 2 port of the extension?

**Comment by mzeis** [comment]
We are not working on M2 projects yet so we didn't start a port. If there is no other tool coming by I guess we will do it one day.

**Comment by jonasvanderhaegen** [comment]
Since it's now half February 2016 is there any update about this? ;)

**Comment by mzeis** [comment]
A justified question. ;-) We discussed about it internally but didn't start development yet.

I'm interested in everyone's opinion:

* Is there already a similar tool for M2?
* Is somebody already working on a port of EnvironmentConfiguration for M2?
* If there is a port, should it be based on [n98-magerun2](https://github.com/netz98/n98-magerun2) or should it be based on the `magento` CLI tool?

**Comment by jonasvanderhaegen** [comment]
- Well we started using this module on M1 since yesterday, (mind is blown that we didn't use this earlier). Was looking for something similar for M2 yea but couldn't find anything that's as impressive and useful as this.

- Don't know if someone made a port, I searched a little bit but no results.

- Preferably based on n98-magerun2 yes, or maybe both?

**Comment by rickstoopman** [comment]
We are using the M1 module for a few months now, and just like @jonasvanderhaegen said we should have started using it years ago!

I'm actually pretty disappointed that no such feature exists in the current Magento2 core.

So yes, I'm very much interesting in a M2 port! I think it'd be best to extend the core magento cli too

**Comment by rickstoopman** [comment]
I did find a similar module for Magento2

https://github.com/semaio/Magento2-ConfigImportExport

**Comment by mzeis** [comment]
@rickstoopman I didn't try it yet myself yet but it looks very nice. Currently we are investigating whether it is necessary to re-write EnvironmentConfiguration or if we just will go with the tools which are already out there (like `Magento2-ConfigImportExport`).

**Comment by mzeis** [comment]
I'm closing this as I don't have plans to re-write the extension for M2 at the moment. There are nice free alternatives out there.
