### ISSUE TITLE
Impossible to use configuration values starting with a dash

### ISSUE THREAD

**Issue by Qronicle** [LimeSoda/LimeSoda_EnvironmentConfiguration#16]
Hi,

When using ls:env:configure, I've noticed it's impossible to set a variable to a value starting with a dash, like '-1'.
This is caused by a known Symfony Console issue (https://github.com/symfony/symfony/pull/3624), and the solution should be fairly straightforward to implement. 

I would make a pull request, but I think you just need to change one line in lib/n98-magerun/modules/LimeSoda_EnvironmentConfiguration/src/LimeSoda/Environment/Configure.php where the config:set commands are executed (line 38):

`$input = new StringInput('-- ' . $command);`
instead of 
`$input = new StringInput($command);`

The '-- ' makes sure no argument values after its appearance are interpreted as option names.

**Comment by mzeis** [comment]
Thanks for your this recommendation! We will have a look at it.

**Comment by mzeis** [comment]
@Qronicle I updated the code to allow negative values when using the `system_configuration` node to set negative values. I also updated the documentation to use `--` when calling `config:set` directly.

Thanks for noticing this!
