### ISSUE TITLE
Is it possible to check Use Default in any way?

### ISSUE THREAD

**Issue by driesatunit** [LimeSoda/LimeSoda_EnvironmentConfiguration#17]
Hi,

I'm also wondering if it is possible to use LimeSode to uncheck and check the "Use Default" checkboxes as seen in the attached screenshot?
![screen shot 2018-05-28 at 14 20 20](https://user-images.githubusercontent.com/39699583/40614231-48fddf88-6282-11e8-8565-2b3fdcae20bf.png)

**Comment by mzeis** [comment]
Hi,

I never had to do this but you can execute any n98-magerun command using LimeSoda_EnvironmentConfiguration, so it might be possible.

For example, if you want to set "Use Default" for a setting in "System > Configuration", this means you have to delete the setting in the given scope and you can do that using [config:delete](https://github.com/netz98/n98-magerun#delete-config):

    <commands>
        <test>config:delete --scope="stores" --scope-id="2" --force "your/config/path"</test>
    </commands>

If you are talking about product or category data, I'm afraid there is more work involved.

Does this help you?

**Comment by driesatunit** [comment]
Thank you for your answer.
Sadly it's not what I need.

What I would like to do is uncheck the "Use Default" checkbox without assigning a value to the config.
For example:
I'm using a different file for shipping table rates per store. These files are stored in different folders and I'm using custom code to get them and load them.
What I would like to do is for some stores to uncheck the "Use Default" checkbox next to where I have to select that file so my different files get used.
I was just wondering of that's possible through LimeSoda or should I use a manual approach.

**Comment by pnlimesoda** [comment]
Sorry, I don't really understand your example, but in general the state (checked or unchecked) of the "Use default" Checkbox is not a value itself that is saved somewhere in the database. The state displayed in the Magento Backend rather results from the saved config values per store view. If you only have one value saved for the default scope of a config path, the checkbox "Use default" will be checked. If you have seperate values for other scopes like "website" or "stores" the checkbox will be unchecked respectively.
So if you want to uncheck or check the checkbox, you have to save or delete a config path's scope value as Matthias mentioned before. I think there is no other way without custom programming.

**Comment by driesatunit** [comment]
Thank you both!!

I'll try and keep it in mind.
It was just something I was wondering about but not really something necessary.
