### ISSUE TITLE
Improve check/handling of ls:env:configure

### ISSUE THREAD

**Issue by mzeis** [LimeSoda/LimeSoda_EnvironmentConfiguration#3]
As suggested by @schmengler and discussed internally, the feature should be implemented like this:
- If no environment name was specified when calling `n98-magerun.phar ls:env:configure`, assume the environment name set in the local configuration
- If the environment is used like that, let the user confirm this choice:
  
  ```
  Configure environment 'mz'? [y,n]
  ```
  
  The user has to confirm this with "y"
- For automation, a "force" parameter can be provided which will automatically confirm the question above
- If the user provides an environment as an argument which is not the one set in the local configuration, stop with a warning/error.
  Example: if environment `abc` is set in `local.xml` but the user executes `n98-magerun.phar ls:env:configure def`, the execution should be stopped.
- The user can provide a "force" parameter to still apply the other configuration.

Note: the naming of the force parameter and the confirmation of the choice is not fixed. If there is a standard way to do/name it in n98-magerun, we can follow that.

A nice to have feature which could be implemented additionally:
- If no environment was added as a parameter, list the existing environments as a select dialog with the configured one being the default

**Comment by mzeis** [comment]
@schmengler I think we talked about this at some event in the meanwhile but: do you still want this to be implemented? If would be a nice feature but if we could live without it so long (or you implemented it in your fork) it might be ok to just close the issue... :-)

**Comment by schmengler** [comment]
I did not implement it either and since we are using the configurator mostly by automated scripts it was not a pain point. So I'm fine with closing the issue as "nice to have but not important enough" :)

**Comment by mzeis** [comment]
Thanks for your response - same here. :-)

I'll close the issue but if somebody needs this feature nonetheless feel free to implement it and send a PR.
